#ifndef UNICODE
#define UNICODE
#endif
#define _UNICODE
#include <windows.h>
#include <string>
#include <vector>
#include <algorithm>
#include <cwctype>
struct Cheat { const wchar_t *category,*code,*title,*note; };
#include "cheats.h"
const COLORREF BG=RGB(14,18,25), PANEL=RGB(23,30,40), TEXT=RGB(230,237,245), MUTED=RGB(152,168,185), GREEN=RGB(110,239,167);
HWND win,searchBox,categories,listBox,copyButton,sendButton,favButton,gameWindow;
HFONT normal,small,big,mono; HBRUSH bgBrush,panelBrush;
std::vector<int> visible; std::wstring status=L"Готово. Запусти одиночную GTA: San Andreas.",pending,iniPath;
bool favorites[sizeof(cheats)/sizeof(cheats[0])]={}; int selected=0, tick=0, phase=0; bool busy=false; WORD heldScan=0;
const int COUNT=sizeof(cheats)/sizeof(cheats[0]);
std::wstring lower(std::wstring s){ for(auto &c:s)c=towlower(c);return s; }
void label(HDC dc,int x,int y,int w,int h,const std::wstring &s,HFONT f,COLORREF color){SelectObject(dc,f);SetTextColor(dc,color);SetBkMode(dc,TRANSPARENT);RECT r={x,y,x+w,y+h};DrawTextW(dc,s.c_str(),-1,&r,DT_LEFT|DT_WORDBREAK|DT_NOPREFIX);}
void refresh(){wchar_t q[256],cat[128];GetWindowTextW(searchBox,q,256);GetWindowTextW(categories,cat,128);auto term=lower(q);SendMessage(listBox,LB_RESETCONTENT,0,0);visible.clear();for(int i=0;i<COUNT;i++){auto &c=cheats[i];if(wcscmp(cat,L"Все категории") && wcscmp(cat,L"Избранное") && wcscmp(cat,c.category))continue;if(!wcscmp(cat,L"Избранное")&&!favorites[i])continue;if(lower(std::wstring(c.title)+L" "+c.code+L" "+c.category+L" "+c.note).find(term)==std::wstring::npos)continue;visible.push_back(i);SendMessage(listBox,LB_ADDSTRING,0,(LPARAM)c.title);}SendMessage(listBox,LB_SETCURSEL,0,0);selected=visible.empty()?-1:visible[0];InvalidateRect(win,NULL,TRUE);}
bool isGame(HWND h){if(!IsWindow(h)||!IsWindowVisible(h))return false;DWORD pid;GetWindowThreadProcessId(h,&pid);HANDLE p=OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION,FALSE,pid);if(!p)return false;wchar_t path[32768];DWORD size=32768;bool ok=QueryFullProcessImageNameW(p,0,path,&size);CloseHandle(p);if(!ok)return false;auto name=lower(path);auto pos=name.find_last_of(L"\\/");if(pos!=std::wstring::npos)name=name.substr(pos+1);return name==L"gta_sa.exe"||name==L"gta-sa.exe";}
BOOL CALLBACK findGame(HWND h,LPARAM){if(isGame(h)){gameWindow=h;return FALSE;}return TRUE;}
void stop(const wchar_t* text){if(heldScan){INPUT release={};release.type=INPUT_KEYBOARD;release.ki.wScan=heldScan;release.ki.dwFlags=KEYEVENTF_SCANCODE|KEYEVENTF_KEYUP;SendInput(1,&release,sizeof(INPUT));heldScan=0;}KillTimer(win,1);busy=false;pending.clear();status=text;EnableWindow(sendButton,TRUE);InvalidateRect(win,NULL,TRUE);}
void copy(){if(selected<0)return;const wchar_t *s=cheats[selected].code;size_t n=(wcslen(s)+1)*sizeof(wchar_t);HGLOBAL mem=GlobalAlloc(GMEM_MOVEABLE,n);if(!mem)return;void* ptr=GlobalLock(mem);if(!ptr){GlobalFree(mem);return;}memcpy(ptr,s,n);GlobalUnlock(mem);if(OpenClipboard(win)){EmptyClipboard();if(!SetClipboardData(CF_UNICODETEXT,mem))GlobalFree(mem);CloseClipboard();status=L"Код скопирован. В GTA набери его вручную — вставка может не работать.";}else{GlobalFree(mem);status=L"Буфер обмена занят. Попробуй ещё раз.";}InvalidateRect(win,NULL,TRUE);}
void activate(){if(busy||selected<0)return;if(MessageBoxW(win,L"Только одиночная игра. Сначала создай отдельное сохранение.\n\nПосле подтверждения откроется GTA. За 3 секунды закрой меню / паузу. В игре выбери английскую раскладку. Не нажимай клавиши во время отправки.\n\nEsc отменяет отправку. Продолжить?",L"Отправка кода в GTA",MB_OKCANCEL|MB_ICONWARNING)!=IDOK)return;gameWindow=NULL;EnumWindows(findGame,0);if(!gameWindow){status=L"GTA не найдена. Нужен gta_sa.exe или gta-sa.exe. Можно скопировать код.";InvalidateRect(win,NULL,TRUE);return;}pending=cheats[selected].code;busy=true;tick=30;phase=0;EnableWindow(sendButton,FALSE);ShowWindow(gameWindow,SW_RESTORE);SetForegroundWindow(gameWindow);SetTimer(win,1,100,NULL);status=L"Отправка через 3 секунды. Esc — отмена.";InvalidateRect(win,NULL,TRUE);}
void timer(){if(GetAsyncKeyState(VK_ESCAPE)&0x8000){stop(L"Отменено клавишей Esc.");return;}if(tick>0){--tick;return;}if(GetForegroundWindow()!=gameWindow||!isGame(gameWindow)){stop(L"Отменено: GTA не в фокусе. Код не будет отправлен в другое окно.");return;}if(GetAsyncKeyState(VK_CONTROL)&0x8000||GetAsyncKeyState(VK_MENU)&0x8000||GetAsyncKeyState(VK_SHIFT)&0x8000){stop(L"Отменено: отпусти Ctrl, Alt и Shift и повтори.");return;}if(phase>=(int)pending.size()){stop(L"Код отправлен. Проверь уведомление в GTA: программа не читает состояние игры.");return;}INPUT input={};input.type=INPUT_KEYBOARD;if(heldScan){input.ki.wScan=heldScan;input.ki.dwFlags=KEYEVENTF_SCANCODE|KEYEVENTF_KEYUP;if(SendInput(1,&input,sizeof(INPUT))!=1){stop(L"Windows заблокировала отпускание клавиши. Отмени ввод и проверь игру.");return;}heldScan=0;++phase;}else{input.ki.wScan=(WORD)MapVirtualKeyExW(pending[phase],MAPVK_VK_TO_VSC,LoadKeyboardLayoutW(L"00000409",0));input.ki.dwFlags=KEYEVENTF_SCANCODE;if(SendInput(1,&input,sizeof(INPUT))!=1){stop(L"Windows заблокировала ввод. Запусти GTA и тул без прав администратора или введи код вручную.");return;}heldScan=input.ki.wScan;}}
HWND control(const wchar_t* cls,const wchar_t* text,DWORD style,int id){HWND h=CreateWindowExW(0,cls,text,WS_CHILD|WS_VISIBLE|style,0,0,0,0,win,(HMENU)(INT_PTR)id,GetModuleHandle(NULL),NULL);SendMessage(h,WM_SETFONT,(WPARAM)normal,TRUE);return h;}
void layout(){RECT r;GetClientRect(win,&r);int w=r.right,h=r.bottom,left=w*52/100;MoveWindow(searchBox,28,114,left-40,34,TRUE);MoveWindow(categories,left+10,114,w-left-38,220,TRUE);MoveWindow(listBox,28,168,left-40,h-258,TRUE);int x=left+14,rw=w-x-28;MoveWindow(sendButton,x,h-235,rw,44,TRUE);MoveWindow(copyButton,x,h-181,rw/2-5,38,TRUE);MoveWindow(favButton,x+rw/2+5,h-181,rw/2-5,38,TRUE);InvalidateRect(win,NULL,TRUE);}
LRESULT CALLBACK proc(HWND h,UINT m,WPARAM wp,LPARAM lp){switch(m){case WM_CREATE:{win=h;normal=CreateFontW(-17,0,0,0,FW_NORMAL,0,0,0,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,0,L"Segoe UI");small=CreateFontW(-14,0,0,0,FW_NORMAL,0,0,0,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,0,L"Segoe UI");big=CreateFontW(-29,0,0,0,FW_BOLD,0,0,0,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,0,L"Segoe UI");mono=CreateFontW(-24,0,0,0,FW_BOLD,0,0,0,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,0,L"Consolas");bgBrush=CreateSolidBrush(BG);panelBrush=CreateSolidBrush(PANEL);searchBox=control(L"EDIT",L"",WS_TABSTOP|ES_AUTOHSCROLL|WS_BORDER,101);SendMessageW(searchBox,0x1501,TRUE,(LPARAM)L"Поиск по названию или коду…");categories=control(L"COMBOBOX",L"",WS_TABSTOP|CBS_DROPDOWNLIST|WS_VSCROLL,102);SendMessage(categories,CB_ADDSTRING,0,(LPARAM)L"Все категории");SendMessage(categories,CB_ADDSTRING,0,(LPARAM)L"Избранное");std::vector<std::wstring> cats;for(auto &c:cheats)if(std::find(cats.begin(),cats.end(),c.category)==cats.end()){cats.push_back(c.category);SendMessage(categories,CB_ADDSTRING,0,(LPARAM)c.category);}SendMessage(categories,CB_SETCURSEL,0,0);listBox=control(L"LISTBOX",L"",WS_TABSTOP|LBS_NOTIFY|LBS_OWNERDRAWFIXED|LBS_HASSTRINGS|WS_VSCROLL|LBS_NOINTEGRALHEIGHT,103);SendMessage(listBox,LB_SETITEMHEIGHT,0,62);sendButton=control(L"BUTTON",L"Отправить в GTA  →",WS_TABSTOP|BS_OWNERDRAW,104);copyButton=control(L"BUTTON",L"Копировать",WS_TABSTOP|BS_OWNERDRAW,105);favButton=control(L"BUTTON",L"В избранное",WS_TABSTOP|BS_OWNERDRAW,106);wchar_t appdata[MAX_PATH];if(GetEnvironmentVariableW(L"LOCALAPPDATA",appdata,MAX_PATH)){iniPath=std::wstring(appdata)+L"\\GroveCodes";CreateDirectoryW(iniPath.c_str(),NULL);iniPath+=L"\\favorites.ini";for(int i=0;i<COUNT;i++)favorites[i]=GetPrivateProfileIntW(L"Favorites",cheats[i].code,0,iniPath.c_str())!=0;}refresh();return 0;}
case WM_SIZE:layout();return 0;
case WM_GETMINMAXINFO:((MINMAXINFO*)lp)->ptMinTrackSize={940,760};return 0;
case WM_COMMAND:if(LOWORD(wp)==101&&HIWORD(wp)==EN_CHANGE)refresh();if(LOWORD(wp)==102&&HIWORD(wp)==CBN_SELCHANGE)refresh();if(LOWORD(wp)==103&&HIWORD(wp)==LBN_SELCHANGE){int idx=SendMessage(listBox,LB_GETCURSEL,0,0);selected=idx>=0&&idx<(int)visible.size()?visible[idx]:-1;InvalidateRect(win,NULL,TRUE);}if(LOWORD(wp)==104)activate();if(LOWORD(wp)==105)copy();if(LOWORD(wp)==106&&selected>=0){favorites[selected]=!favorites[selected];if(!iniPath.empty())WritePrivateProfileStringW(L"Favorites",cheats[selected].code,favorites[selected]?L"1":L"0",iniPath.c_str());InvalidateRect(listBox,NULL,TRUE);InvalidateRect(win,NULL,TRUE);}return 0;
case WM_TIMER:timer();return 0;
case WM_CTLCOLOREDIT:case WM_CTLCOLORLISTBOX:SetTextColor((HDC)wp,TEXT);SetBkColor((HDC)wp,PANEL);return (LRESULT)panelBrush;
case WM_DRAWITEM:{auto d=(DRAWITEMSTRUCT*)lp;if(d->CtlID==103){if(d->itemID==(UINT)-1||d->itemID>=visible.size())return TRUE;int i=visible[d->itemID];bool active=d->itemState&ODS_SELECTED;HBRUSH b=CreateSolidBrush(active?RGB(34,66,54):PANEL);FillRect(d->hDC,&d->rcItem,b);DeleteObject(b);int x=d->rcItem.left+14,y=d->rcItem.top+9,w=d->rcItem.right-x-12;label(d->hDC,x,y,w,23,(favorites[i]?L"★  ":L"")+std::wstring(cheats[i].title),normal,active?GREEN:TEXT);label(d->hDC,x,y+25,w,21,std::wstring(cheats[i].category)+L"   /   "+cheats[i].code,small,MUTED);}else{bool primary=d->CtlID==104;HBRUSH b=CreateSolidBrush(primary?GREEN:RGB(39,49,63));FillRect(d->hDC,&d->rcItem,b);DeleteObject(b);wchar_t text[128];GetWindowTextW(d->hwndItem,text,128);SelectObject(d->hDC,normal);SetBkMode(d->hDC,TRANSPARENT);SetTextColor(d->hDC,primary?BG:TEXT);DrawTextW(d->hDC,text,-1,&d->rcItem,DT_CENTER|DT_VCENTER|DT_SINGLELINE);if(d->itemState&ODS_FOCUS)DrawFocusRect(d->hDC,&d->rcItem);}return TRUE;}
case WM_PAINT:{PAINTSTRUCT ps;HDC dc=BeginPaint(h,&ps);RECT r;GetClientRect(h,&r);FillRect(dc,&r,bgBrush);int x=r.right*52/100+14,w=r.right-x-28;label(dc,28,22,600,40,L"GROVE / CODES",big,TEXT);label(dc,30,66,800,25,L"SAN ANDREAS CLASSIC     •     SINGLE PLAYER     •     v1.0.0",small,GREEN);if(selected>=0){auto &c=cheats[selected];label(dc,x,176,w,25,c.category,small,GREEN);label(dc,x,212,w,85,c.title,big,TEXT);label(dc,x,305,w,45,c.code,mono,GREEN);label(dc,x,367,w,88,c.note,normal,MUTED);}else label(dc,x,200,w,120,L"Ничего не найдено.\nИзмени запрос или категорию.",normal,MUTED);label(dc,28,r.bottom-77,r.right-56,25,L"Найдено: "+std::to_wstring(visible.size())+L" / "+std::to_wstring(COUNT)+L"   •   Сделай отдельное сохранение. Не используй в SA-MP / MTA.",small,MUTED);label(dc,28,r.bottom-48,r.right-56,45,status,small,GREEN);EndPaint(h,&ps);return 0;}
case WM_DESTROY:stop(L"Закрытие программы.");DeleteObject(normal);DeleteObject(small);DeleteObject(big);DeleteObject(mono);DeleteObject(bgBrush);DeleteObject(panelBrush);PostQuitMessage(0);return 0;}return DefWindowProcW(h,m,wp,lp);}
int WINAPI wWinMain(HINSTANCE inst,HINSTANCE,LPWSTR,int show){SetProcessDPIAware();WNDCLASSW wc={};wc.lpfnWndProc=proc;wc.hInstance=inst;wc.lpszClassName=L"GroveCodesWindow";wc.hCursor=LoadCursor(NULL,IDC_ARROW);wc.hIcon=LoadIconW(inst,MAKEINTRESOURCEW(1));RegisterClassW(&wc);HWND h=CreateWindowExW(0,wc.lpszClassName,L"Grove Codes — GTA San Andreas Classic",WS_OVERLAPPEDWINDOW,CW_USEDEFAULT,CW_USEDEFAULT,1040,760,NULL,NULL,inst,NULL);ShowWindow(h,show);MSG msg;while(GetMessageW(&msg,NULL,0,0)>0){if(!IsDialogMessageW(h,&msg)){TranslateMessage(&msg);DispatchMessageW(&msg);}}return 0;}
